CREATE DATABASE bakerydb;

use bakerydb;

SELECT * FROM goods;

DESC GOODS;

SELECT PRICE,FOOD FROM GOODS;

SELECT ID FROM GOODS;

SELECT * FROM GOODS WHERE PRICE=3.25;

SELECT * FROM GOODS WHERE PRICE=3.25 OR PRICE = 8.95;

SELECT * FROM GOODS WHERE PRICE<>3.25 AND PRICE <>8.95;

SELECT * FROM GOODS WHERE PRICE>3;

SELECT * FROM GOODS WHERE FOOD LIKE "%H%";

SELECT * FROM GOODS WHERE FOOD LIKE "%RT";

SELECT * FROM GOODS WHERE FOOD LIKE "____";

SELECT * FROM GOODS WHERE FOOD LIKE "%KE" OR PRICE > 3;

SELECT * FROM GOODS WHERE PRICE IN (3.25,8.95,3.75);

SELECT * FROM GOODS WHERE FOOD NOT LIKE "____";

INSERT INTO GOODS (ID,FLAVOR,FOOD,PRICE) VALUE (2121,"VANILA","COOKIES",NULL);

SELECT * FROM GOODS WHERE PRICE IS NULL;

SELECT * FROM GOODS WHERE PRICE BETWEEN 3.25 AND 8.95;

SELECT * FROM GOODS ORDER BY PRICE ;

SELECT * FROM GOODS ORDER BY PRICE DESC;


 