CREATE DATABASE cardb;

use cardb;

DESC carmakers;

SELECT *FROM carmakers;

SELECT MAKER,COUNTRY FROM CARMAKERS;

SELECT MAKER FROM CARMAKERS;

SELECT * FROM CARMAKERS WHERE COUNTRY=4;

SELECT * FROM CARMAKERS WHERE COUNTRY=2 OR COUNTRY=5;

SELECT * FROM CARMAKERS WHERE COUNTRY<>2 AND COUNTRY<>5;

SELECT * FROM CARMAKERS WHERE COUNTRY>2;

SELECT * FROM CARMAKERS WHERE MAKER LIKE "%DA";

SELECT * FROM CARMAKERS WHERE MAKER LIKE "____";

SELECT * FROM CARMAKERS WHERE MAKER LIKE "%EN" AND COUNTRY=2;

SELECT * FROM CARMAKERS WHERE COUNTRY IN (2,3,4,5);

SELECT * FROM CARMAKERS WHERE MAKER NOT LIKE "____";

INSERT INTO CARMAKERS (MAKER,FULLNAME,COUNTRY) VALUE ("AD","AUDI",NULL);

SELECT * FROM CARMAKERS WHERE COUNTRY IS NULL;

SELECT * FROM CARMAKERS WHERE COUNTRY BETWEEN 2 AND 5;

SELECT * FROM CARMAKERS ORDER BY COUNTRY;



