CREATE DATABASE zoodb;
USE zoodb;
DESC zoo;

SELECT * FROM zoo WHERE uniq_id IN (1001,1008,1012,1015,1018);


SELECT * FROM zoo WHERE animal NOT LIKE "_____";

SELECT * FROM zoo WHERE ANIMAL="DOG" AND WATER_NEED IS NULL;

SELECT * FROM zoo WHERE WATER_NEED BETWEEN 400 AND 600;

SELECT * FROM zoo ORDER BY WATER_NEED DESC;

INSERT INTO ZOO (animal,UNIQ_ID,water_need) value ("dog",1234,NULL);